### ISSUE TITLE
Upload a log file - Secure Connection Failed

### ISSUE THREAD

**Issue by AnnanFay** [rconroy293/mtga-log-client#21]
I tried uploading a 34mb log file to [this page](https://www.17lands.com/upload) and got a ["Secure Connection Failed" error](https://i.imgur.com/4yjnFtc.png).

I'd suggest maybe removing the feature or requiring zip compression. Log files can become *very* large. Even if the server is fine with the load users would probably appreciate uploading compressed files.

Alternatively the client could allow uploading files and do client-side compression. I have a few months of backed up log files I wouldn't mind uploading.

**Comment by rconroy293** [comment]
Apologies for the delay on this - I've opted to remove the feature. Thanks for reporting!
