### ISSUE TITLE
Date selector issue on 17lands.com

### ISSUE THREAD

**Issue by MHova** [rconroy293/mtga-log-client#45]
This is certainly not the right repo for this, but here goes:

Looks like there's a cool new date selector feature on the "My Data" page on 17lands.com. I think there's an off-by-one error with the end date.

In the following screenshot, the end date is `5/25/2020` and does not include results from `5/25/2020`:
![image](https://user-images.githubusercontent.com/5972021/82844033-d8a08100-9e93-11ea-8fc9-06ad789ff0bd.png)

But if I change the end date to `5/26/2020`, the results from `5/25/2020` are included:
![image](https://user-images.githubusercontent.com/5972021/82844107-14d3e180-9e94-11ea-9986-a2299f884b96.png)

As a user, I would expect the date selector range to be inclusive on both ends.

**Comment by rconroy293** [comment]
Thanks for the report - I'll put out a fix right now!

**Comment by rconroy293** [comment]
Should be fixed now. If you prefer, feel free to DM / tweet @17Lands if you run into other issues!

**Comment by MHova** [comment]
Awesome, thank you!
